title:            阳城雨林
description:      这是林诚霖的个人博客，欢迎访问。

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: http://www.lezic.com

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: '首页'
    url: '/'
  - title: '标签'
    url: '/tags'
  - title: '分类'
    url: '/categories'
    type: 'categories'
  - title: '最爱'
    url: '#'
    submenu:
    #  - title: 'Code Highlighter'
    #    url: '/intro/code-highlighting-post/'
    #  - title: 'Sample Post'
    #    url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           林诚霖
  site:           http://www.lezic.com
  avatar:         images/avatar.jpg
  bio:            "每个今天总能看见昨天傻傻的自己</br>愿不再执着过去</br>愿不再迷茫未来"
  email:          babytiana@sina.com
  # Twitter nick for use in Twitter cards and follow button.
  # twitter: aron_bordin # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: icielo
  weibo: 2097636277

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
#  - title: "github"
#    url: "https://github.com/icielo"
#  - title: "linkedin"
#    url: "https://br.linkedin.com/in/aronbordin"
#  - title: "youtube"
#    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
locale:      zh_CN
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
